# Change these first
owner: rohanmathias # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Portal
    url: https://portal.rocketprotpo.com/v2/
